#pragma once

#include <stddef.h>

static const char HTML_INDEX_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>LOTSE Config Hub</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f0f2f5;color:#333;padding:16px;max-width:900px;margin:0 auto}\n"
    "h1{font-size:20px;margin:8px 0 16px;color:#1a237e}\n"
    "h2{font-size:16px;margin:16px 0 8px;color:#283593}\n"
    ".card{background:#fff;border-radius:8px;padding:16px;margin-bottom:12px;box-shadow:0 1px 3px rgba(0,0,0,.12)}\n"
    ".status{display:flex;gap:12px;flex-wrap:wrap}\n"
    ".status-item{padding:6px 12px;border-radius:16px;font-size:13px;font-weight:600}\n"
    ".status-ok{background:#e8f5e9;color:#2e7d32}\n"
    ".status-warn{background:#fff3e0;color:#e65100}\n"
    ".status-err{background:#fbe9e7;color:#c62828}\n"
    "label{display:block;font-size:13px;font-weight:600;margin:8px 0 4px;color:#555}\n"
    "input,textarea,select{width:100%;padding:8px 12px;border:1px solid #ccc;border-radius:6px;font-size:14px}\n"
    "textarea{font-family:'Courier New',monospace;font-size:12px;min-height:120px;resize:vertical}\n"
    "table{width:100%;border-collapse:collapse;margin:8px 0}\n"
    "th,td{padding:6px 8px;text-align:left;border-bottom:1px solid #e0e0e0;font-size:13px}\n"
    "th{background:#f5f5f5;font-weight:600}\n"
    "select{padding:4px 6px;font-size:12px}\n"
    ".btn{padding:10px 20px;border:none;border-radius:6px;font-size:14px;font-weight:600;cursor:pointer;display:inline-flex;align-items:center;gap:6px}\n"
    ".btn-primary{background:#3949ab;color:#fff}\n"
    ".btn-primary:hover{background:#303f9f}\n"
    ".btn-primary:disabled{background:#9fa8da;cursor:not-allowed}\n"
    ".btn-secondary{background:#e0e0e0;color:#333}\n"
    ".btn-secondary:hover{background:#bdbdbd}\n"
    ".btn-success{background:#2e7d32;color:#fff}\n"
    ".btn-success:hover{background:#1b5e20}\n"
    ".btn-danger{background:#c62828;color:#fff}\n"
    ".toast{position:fixed;bottom:24px;right:24px;padding:12px 20px;border-radius:8px;color:#fff;font-weight:600;font-size:14px;z-index:100;animation:fadeIn .3s}\n"
    ".toast-success{background:#2e7d32}\n"
    ".toast-error{background:#c62828}\n"
    ".toast-info{background:#1565c0}\n"
    "@keyframes fadeIn{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}\n"
    ".hidden{display:none!important}\n"
    "#spinner{display:inline-block;width:16px;height:16px;border:2px solid #9fa8da;border-top-color:#3949ab;border-radius:50%;animation:spin .6s linear infinite;vertical-align:middle;margin-right:6px}\n"
    "@keyframes spin{to{transform:rotate(360deg)}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<h1>&#9889; LOTSE Config Hub</h1>\n"
    "\n"
    "<div id=\"wifi-setup\" class=\"card hidden\">\n"
    "  <h2>WiFi Setup</h2>\n"
    "  <p style=\"font-size:13px;color:#666;margin-bottom:8px\">Select and connect to a WiFi network.</p>\n"
    "  <div style=\"display:flex;gap:8px;align-items:center;margin-bottom:8px\">\n"
    "    <button class=\"btn btn-secondary\" onclick=\"scanWifi('wifi-setup')\">&#128269; Scan networks</button>\n"
    "    <span id=\"wifi-setup-scan-msg\" style=\"font-size:13px;color:#666\"></span>\n"
    "  </div>\n"
    "  <label>Network</label>\n"
    "  <select id=\"wifi-setup-ssid\" onchange=\"onSsidChange('wifi-setup')\">\n"
    "    <option value=\"\">&mdash; Select network &mdash;</option>\n"
    "  </select>\n"
    "  <div id=\"wifi-setup-manual\" class=\"hidden\" style=\"margin-top:8px\">\n"
    "    <label>Manual SSID</label>\n"
    "    <input id=\"wifi-setup-ssid-manual\" placeholder=\"e.g. FRITZ!Box 7590\">\n"
    "  </div>\n"
    "  <label>Password</label>\n"
    "  <input id=\"wifi-setup-pass\" type=\"password\" placeholder=\"WiFi password\">\n"
    "  <div style=\"display:flex;gap:8px;align-items:center;margin-top:12px\">\n"
    "    <button class=\"btn btn-primary\" onclick=\"saveWifi('wifi-setup')\">Connect</button>\n"
    "    <span id=\"wifi-setup-msg\" style=\"font-size:13px;color:#666\"></span>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"diff-modal\" class=\"hidden\" style=\"position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.4);z-index:200;display:flex;align-items:center;justify-content:center\">\n"
    "  <div style=\"background:#fff;border-radius:12px;padding:24px;max-width:500px;width:90%;box-shadow:0 4px 24px rgba(0,0,0,.3)\">\n"
    "    <h2 style=\"margin:0 0 4px\">Differences found on Tasmota</h2>\n"
    "    <p style=\"font-size:13px;color:#666;margin-bottom:12px\">Select what to send:</p>\n"
    "    <div id=\"diff-items\" style=\"margin-bottom:16px\"></div>\n"
    "    <div style=\"display:flex;gap:8px;justify-content:flex-end\">\n"
    "      <button class=\"btn btn-secondary\" onclick=\"closeDiffModal()\">Cancel</button>\n"
    "      <button id=\"diff-send-btn\" class=\"btn btn-success\" onclick=\"sendSelectedActions()\">&#128228; Send selected</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"main-ui\" class=\"hidden\">\n"
    "  <div class=\"card\">\n"
    "    <h2>Status</h2>\n"
    "    <div class=\"status\">\n"
    "      <span id=\"status-wifi\" class=\"status-item\">WiFi: ?</span>\n"
    "      <span id=\"status-mqtt\" class=\"status-item\">MQTT: ?</span>\n"
    "      <span id=\"status-tasmota\" class=\"status-item\">Tasmota: ?</span>\n"
    "      <span id=\"status-ip\" class=\"status-item\">IP: -</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>WiFi</h2>\n"
    "    <div style=\"display:flex;gap:8px;align-items:center;margin-bottom:8px\">\n"
    "      <button class=\"btn btn-secondary\" onclick=\"scanWifi('main')\">&#128269; Scan networks</button>\n"
    "      <span id=\"wifi-main-scan-msg\" style=\"font-size:13px;color:#666\"></span>\n"
    "    </div>\n"
    "    <label>Network</label>\n"
    "    <select id=\"wifi-main-ssid\" onchange=\"onSsidChange('main')\">\n"
    "      <option value=\"\">&mdash; Select network &mdash;</option>\n"
    "    </select>\n"
    "    <div id=\"wifi-main-manual\" class=\"hidden\" style=\"margin-top:8px\">\n"
    "      <label>Manual SSID</label>\n"
    "      <input id=\"wifi-main-ssid-manual\" placeholder=\"e.g. FRITZ!Box 7590\">\n"
    "    </div>\n"
    "    <label>Password</label>\n"
    "    <input id=\"wifi-main-pass\" type=\"password\" placeholder=\"WiFi password\">\n"
    "    <div style=\"display:flex;gap:8px;align-items:center;margin-top:12px\">\n"
    "      <button class=\"btn btn-primary\" onclick=\"saveWifi('main')\">Connect</button>\n"
    "      <span id=\"wifi-main-msg\" style=\"font-size:13px;color:#666\"></span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>Configure IR Reader</h2>\n"
    "\n"
    "    <label>IR reader Tasmota IP</label>\n"
    "    <input id=\"tasmota-ip\" placeholder=\"e.g. 192.168.1.100\">\n"
    "    <div style=\"display:flex;gap:8px;align-items:center;margin-top:8px\">\n"
    "      <button class=\"btn btn-secondary\" onclick=\"discoverTasmota()\">&#128269; Discover</button>\n"
    "      <span id=\"discover-msg\" style=\"font-size:13px;color:#666\"></span>\n"
    "    </div>\n"
    "    <div style=\"display:flex;gap:8px;align-items:center;margin-top:4px\">\n"
    "      <button class=\"btn btn-secondary\" onclick=\"verifyTasmota()\">&#128269; Verify script on Tasmota</button>\n"
    "      <span id=\"verify-msg\" style=\"font-size:13px;color:#666\"></span>\n"
    "    </div>\n"
    "\n"
    "    <label style=\"margin-top:16px\">Paste Tasmota script from Hichi / Tasmota docs</label>\n"
    "    <textarea id=\"script-input\" placeholder=\"Paste the SMI script from the Hichi list or Tasmota docs...\"></textarea>\n"
    "    <div style=\"display:flex;gap:8px;margin-top:8px\">\n"
    "      <button class=\"btn btn-primary\" onclick=\"parseScript()\">&#128269; Parse &amp; show variables</button>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"gpio-card\" class=\"card hidden\">\n"
    "    <h2>GPIO pins for SML communication</h2>\n"
    "    <div style=\"display:flex;gap:16px;flex-wrap:wrap\">\n"
    "      <div style=\"flex:1;min-width:120px\">\n"
    "        <label>RX GPIO</label>\n"
    "        <input id=\"gpio-rx\" type=\"number\" value=\"3\" min=\"0\" max=\"39\">\n"
    "      </div>\n"
    "      <div style=\"flex:1;min-width:120px\">\n"
    "        <label>TX GPIO</label>\n"
    "        <input id=\"gpio-tx\" type=\"number\" value=\"1\" min=\"0\" max=\"39\">\n"
    "      </div>\n"
    "    </div>\n"
    "    <div id=\"gpio-warning\" class=\"hidden\" style=\"margin-top:8px;padding:8px 12px;background:#fff3e0;border-radius:6px;font-size:13px;color:#e65100\">\n"
    "      <span id=\"gpio-warning-msg\"></span>\n"
    "    </div>\n"
    "    <label style=\"margin-top:8px;display:flex;align-items:center;gap:8px;font-size:13px;font-weight:400\">\n"
    "      <input id=\"gpio-confirm\" type=\"checkbox\">\n"
    "      I have checked and confirmed the GPIO pins\n"
    "    </label>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"mapping-card\" class=\"card hidden\">\n"
    "    <h2>Map variables to LOTSE keys</h2>\n"
    "    <p style=\"font-size:13px;color:#666;margin-bottom:8px\">Mapping is auto-suggested based on unit. Adjust as needed.</p>\n"
    "    <table>\n"
    "      <thead><tr><th>Variable</th><th>Label</th><th>Unit</th><th>LOTSE Key</th></tr></thead>\n"
    "      <tbody id=\"mapping-table\"></tbody>\n"
    "    </table>\n"
    "  </div>\n"
    "\n"
    "  <div id=\"send-card\" class=\"card hidden\">\n"
    "    <h2>Send configuration to Tasmota</h2>\n"
    "    <div id=\"send-summary\" style=\"font-size:13px;padding:8px 12px;background:#e8f5e9;border-radius:6px;margin-bottom:8px;line-height:1.5\"></div>\n"
    "    <div style=\"display:flex;gap:8px;align-items:center\">\n"
    "      <button id=\"apply-btn\" class=\"btn btn-success\" onclick=\"applyConfig()\">&#128228; Apply &amp; send to Tasmota</button>\n"
    "      <span id=\"apply-msg\" style=\"font-size:13px\"></span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>MQTT Broker</h2>\n"
    "    <table>\n"
    "      <tr><td>Status</td><td id=\"mqtt-status-txt\">-</td></tr>\n"
    "      <tr><td>Connected clients</td><td id=\"mqtt-clients\">0</td></tr>\n"
    "      <tr><td>Port</td><td>1883</td></tr>\n"
    "    </table>\n"
    "    <div style=\"margin-top:8px;display:flex;align-items:center;gap:12px\">\n"
    "      <a href=\"#\" onclick=\"toggleBrokerLog();return false\" id=\"broker-log-toggle\" style=\"font-size:12px;color:#3949ab\">&#9654; Show broker log</a>\n"
    "      <button type=\"button\" onclick=\"copyBrokerLog()\" style=\"font-size:11px;padding:2px 8px;cursor:pointer\">&#128203; Copy</button>\n"
    "    </div>\n"
    "    <div id=\"broker-log-card\" class=\"hidden\" style=\"margin-top:8px\">\n"
    "      <pre id=\"broker-log\" style=\"max-height:400px;overflow-y:auto;font-size:11px;background:#1e1e1e;color:#d4d4d4;padding:8px;border-radius:4px;white-space:pre-wrap;word-break:break-all\">Waiting for data...</pre>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>LOTSE Configuration</h2>\n"
    "    <label>Region</label>\n"
    "    <select id=\"region\">\n"
    "      <option value=\"EU_868\">EU_868</option>\n"
    "      <option value=\"US_915\">US_915</option>\n"
    "      <option value=\"CN_470\">CN_470</option>\n"
    "    </select>\n"
    "    <label>Own node decimal</label>\n"
    "    <input id=\"node-decimal\" type=\"number\" placeholder=\"e.g. 2892010904\">\n"
    "    <label>Send interval (seconds)</label>\n"
    "    <input id=\"send-interval\" type=\"number\" value=\"300\" min=\"60\" max=\"3600\">\n"
    "    <span style=\"font-size:12px;color:#666\">How often data is sent via LoRa (60–3600)</span>\n"
    "    <label>Heltec V3 node hash</label>\n"
    "    <div style=\"display:flex;gap:8px;align-items:center\">\n"
    "      <input id=\"node-hash\" placeholder=\"e.g. !acaad598\" style=\"flex:1\">\n"
    "      <button class=\"btn btn-secondary\" onclick=\"detectNodeHash()\" title=\"Detect from MQTT traffic\">&#128269; Detect</button>\n"
    "    </div>\n"
    "    <span style=\"font-size:12px;color:#666\">The <code>!xxxxxxx</code> suffix from <code>msh/.../json/mqtt/!xxxxxxx</code> topics</span>\n"
    "    <button class=\"btn btn-primary\" onclick=\"saveConfig()\" style=\"margin-top:12px\">Save</button>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"card\">\n"
    "    <h2>Factory Reset</h2>\n"
    "    <p style=\"font-size:13px;color:#666;margin-bottom:8px\">Reset all settings and return to AP mode.</p>\n"
    "    <button class=\"btn btn-danger\" onclick=\"factoryReset()\">&#9888;&#65039; Factory reset</button>\n"
    "    <span id=\"reset-msg\" style=\"font-size:13px;margin-left:8px\"></span>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "const LOTSE_KEYS = [\n"
    "  \"gP\",\"gIP\",\"gEP\",\"gP1\",\"gP2\",\"gP3\",\n"
    "  \"gV1\",\"gV2\",\"gV3\",\"gEI\",\"gEO\",\n"
    "  \"sP\",\"sE\",\"bP\",\"bS\",\"bEI\",\"bEO\",\n"
    "  \"wP\",\"wE\",\"wS\"\n"
    "];\n"
    "\n"
    "function $(id){return document.getElementById(id)}\n"
    "\n"
    "function escHtml(s){\n"
    "  const d=document.createElement('div');\n"
    "  d.textContent=s;\n"
    "  return d.innerHTML;\n"
    "}\n"
    "\n"
    "function toast(msg, type){\n"
    "  const t=document.createElement('div');\n"
    "  t.className='toast toast-'+type;\n"
    "  t.textContent=msg;\n"
    "  document.body.appendChild(t);\n"
    "  setTimeout(()=>t.remove(),4000);\n"
    "}\n"
    "\n"
    "let currentMappings=[];\n"
    "let scriptGpioRx=null;\n"
    "let scriptGpioTx=null;\n"
    "let diffData=null;\n"
    "\n"
    "async function api(path, opts){\n"
    "  try{\n"
    "    console.log('API call:', path, opts);\n"
    "    const r=await fetch(path, opts||{});\n"
    "    console.log('API response status:', r.status);\n"
    "    if(!r.ok) throw new Error(r.statusText);\n"
    "    const result = await r.json();\n"
    "    console.log('API response data:', result);\n"
    "    return result;\n"
    "  }catch(e){\n"
    "    console.error('API error:', e);\n"
    "    toast('API error: '+e.message, 'error');\n"
    "    throw e;\n"
    "  }\n"
    "}\n"
    "\n"
    "function wifiPrefix(prefix){return prefix.startsWith('wifi-')?prefix:'wifi-'+prefix}\n"
    "function ssidId(prefix){return wifiPrefix(prefix)+'-ssid'}\n"
    "function manualId(prefix){return wifiPrefix(prefix)+'-ssid-manual'}\n"
    "function passId(prefix){return wifiPrefix(prefix)+'-pass'}\n"
    "function manualDivId(prefix){return wifiPrefix(prefix)+'-manual'}\n"
    "function scanMsgId(prefix){return wifiPrefix(prefix)+'-scan-msg'}\n"
    "function msgId(prefix){return wifiPrefix(prefix)+'-msg'}\n"
    "\n"
    "function onSsidChange(prefix){\n"
    "  const sel=$(ssidId(prefix));\n"
    "  const div=$(manualDivId(prefix));\n"
    "  if(sel.value==='__manual__'){\n"
    "    div.classList.remove('hidden');\n"
    "  }else{\n"
    "    div.classList.add('hidden');\n"
    "  }\n"
    "}\n"
    "\n"
    "function ensureCurrentSsid(prefix){\n"
    "  const sel=$(ssidId(prefix));\n"
    "  const saved=$(manualId(prefix)).value.trim();\n"
    "  if(!saved) return;\n"
    "  let found=false;\n"
    "  for(let i=0;i<sel.options.length;i++){\n"
    "    if(sel.options[i].value===saved){found=true;break;}\n"
    "  }\n"
    "  if(!found){\n"
    "    const opt=document.createElement('option');\n"
    "    opt.value=saved;\n"
    "    opt.textContent='⚡ '+saved+' (current)';\n"
    "    sel.insertBefore(opt, sel.options[0]);\n"
    "  }\n"
    "  sel.value=saved;\n"
    "}\n"
    "\n"
    "async function scanWifi(prefix){\n"
    "  const msgSpan=$(scanMsgId(prefix));\n"
    "  console.log('scanWifi:', prefix, 'msgSpan:', msgSpan);\n"
    "  if (!msgSpan) {\n"
    "    console.error('scanWifi: msgSpan element not found for prefix:', prefix);\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  const sel=$(ssidId(prefix));\n"
    "  console.log('scanWifi:', prefix, 'sel:', sel);\n"
    "  if (!sel) {\n"
    "    console.error('scanWifi: sel element not found for prefix:', prefix);\n"
    "    msgSpan.textContent='Scan failed: dropdown not found';\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  msgSpan.textContent='Scanning...';\n"
    "  try {\n"
    "    await api('/api/wifi/scan');\n"
    "    let r, deadline=Date.now()+10000;\n"
    "    while(Date.now()<deadline){\n"
    "      await new Promise(r=>setTimeout(r,500));\n"
    "      r=await api('/api/wifi/networks');\n"
    "      if(r.count>0) break;\n"
    "    }\n"
    "    sel.innerHTML='<option value=\"\">&mdash; Select network &mdash;</option>';\n"
    "    if(r&&r.networks){\n"
    "      r.networks.forEach(n=>{\n"
    "        if(!n.ssid) return;\n"
    "        const opt=document.createElement('option');\n"
    "        opt.value=n.ssid;\n"
    "        const icon=n.auth===0?'&#128274;':'&#128274;';\n"
    "        opt.textContent=icon+' '+n.ssid+' ('+n.rssi+' dBm)';\n"
    "        sel.appendChild(opt);\n"
    "      });\n"
    "    }\n"
    "    const manual=document.createElement('option');\n"
    "    manual.value='__manual__';\n"
    "    manual.textContent='&#9998; Other network (manual)';\n"
    "    sel.appendChild(manual);\n"
    "    const c=r&&r.count?r.count:0;\n"
    "    msgSpan.textContent=c+' networks found';\n"
    "    ensureCurrentSsid(prefix);\n"
    "  } catch(e) {\n"
    "    console.error('scanWifi error:', e);\n"
    "    msgSpan.textContent='Scan failed';\n"
    "  }\n"
    "}\n"
    "\n"
    "async function saveWifi(prefix){\n"
    "  const sel=$(ssidId(prefix));\n"
    "  let ssid=sel.value;\n"
    "  if(ssid==='__manual__'||ssid===''){\n"
    "    ssid=$(manualId(prefix)).value.trim();\n"
    "  }\n"
    "  const pass=$(passId(prefix)).value.trim();\n"
    "  const msgSpan=$(msgId(prefix));\n"
    "  if(!ssid) return toast('Enter SSID','error');\n"
    "\n"
    "  msgSpan.innerHTML='<span id=\"spinner\"></span>Saving...';\n"
    "  try{\n"
    "    await api('/api/config',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({wifi_ssid:ssid,wifi_pass:pass,configured:true})\n"
    "    });\n"
    "    msgSpan.textContent='Connecting...';\n"
    "    await api('/api/wifi/connect',{method:'POST'});\n"
    "    toast('WiFi settings saved. Connecting...','info');\n"
    "    setTimeout(()=>init(),3000);\n"
    "  }catch(e){\n"
    "    msgSpan.textContent='Failed';\n"
    "  }\n"
    "}\n"
    "\n"
    "async function refreshStatus(){\n"
    "  try{\n"
    "    const s=await api('/api/status');\n"
    "    const wifi=$('status-wifi');\n"
    "    wifi.textContent='WiFi: '+s.wifi_state;\n"
    "    wifi.className='status-item '+(s.wifi_state==='STATION'?'status-ok':s.wifi_state==='AP'?'status-warn':'status-err');\n"
    "    $('status-ip').textContent='IP: '+(s.ip||'-');\n"
    "    const mqtt=$('status-mqtt');\n"
    "    mqtt.textContent='MQTT: '+s.mqtt_clients+' clients';\n"
    "    mqtt.className='status-item '+(s.mqtt_clients>0?'status-ok':'status-warn');\n"
    "    const tas=$('status-tasmota');\n"
    "    if(s.tasmota_connected){\n"
    "      tas.textContent='Tasmota: connected';\n"
    "      tas.className='status-item status-ok';\n"
    "    }else{\n"
    "      tas.textContent='Tasmota: ?';\n"
    "      tas.className='status-item status-warn';\n"
    "    }\n"
    "    $('mqtt-status-txt').textContent=s.mqtt_clients>0?'Active':'Waiting for clients...';\n"
    "    $('mqtt-clients').textContent=s.mqtt_clients;\n"
    "  }catch(e){}\n"
    "}\n"
    "\n"
    "async function init(){\n"
    "  try{\n"
    "    const cfg=await api('/api/config');\n"
    "    if(cfg.configured){\n"
    "      $('main-ui').classList.remove('hidden');\n"
    "      $('wifi-setup').classList.add('hidden');\n"
    "      if(cfg.wifi_ssid){\n"
    "        $('wifi-main-ssid-manual').value=cfg.wifi_ssid;\n"
    "        ensureCurrentSsid('main');\n"
    "      }\n"
    "      if(cfg.tasmota_ip) $('tasmota-ip').value=cfg.tasmota_ip;\n"
    "      if(cfg.region) $('region').value=cfg.region;\n"
    "      if(cfg.node_decimal) $('node-decimal').value=cfg.node_decimal;\n"
    "      if(cfg.send_interval) $('send-interval').value=cfg.send_interval;\n"
    "      if(cfg.node_hash) $('node-hash').value=cfg.node_hash;\n"
    "      if(cfg.gpio_rx>0) $('gpio-rx').value=cfg.gpio_rx;\n"
    "      if(cfg.gpio_tx>0) $('gpio-tx').value=cfg.gpio_tx;\n"
    "      if(cfg.script) $('script-input').value=cfg.script;\n"
    "      if(cfg.mappings&&cfg.mappings.length){\n"
    "        currentMappings=cfg.mappings;\n"
    "        renderMappings();\n"
    "      }\n"
    "      if (cfg.script) {\n"
    "        try{\n"
    "          const r=await api('/api/script/parse',{\n"
    "            method:'POST',\n"
    "            headers:{'Content-Type':'application/json'},\n"
    "            body:JSON.stringify({script:cfg.script})\n"
    "          });\n"
    "          scriptGpioRx=r.gpio_rx||0;\n"
    "          scriptGpioTx=r.gpio_tx||0;\n"
    "        }catch(e){\n"
    "          scriptGpioRx=0;\n"
    "          scriptGpioTx=0;\n"
    "        }\n"
    "        $('gpio-card').classList.remove('hidden');\n"
    "        $('mapping-card').classList.remove('hidden');\n"
    "        $('send-card').classList.remove('hidden');\n"
    "        updateGpioCard();\n"
    "        updateSendSummary();\n"
    "      }\n"
    "    }else{\n"
    "      $('wifi-setup').classList.remove('hidden');\n"
    "      $('main-ui').classList.add('hidden');\n"
    "    }\n"
    "    refreshStatus();\n"
    "    setInterval(refreshStatus,5000);\n"
    "  }catch(e){}\n"
    "}\n"
    "\n"
    "let brokerLogVisible=false;\n"
    "let brokerLogInterval=null;\n"
    "\n"
    "function toggleBrokerLog(){\n"
    "  const card=$('broker-log-card');\n"
    "  const toggle=$('broker-log-toggle');\n"
    "  brokerLogVisible=!brokerLogVisible;\n"
    "  if(brokerLogVisible){\n"
    "    card.classList.remove('hidden');\n"
    "    toggle.innerHTML='&#9660; Hide broker log';\n"
    "    refreshBrokerLog();\n"
    "    brokerLogInterval=setInterval(refreshBrokerLog,2000);\n"
    "  }else{\n"
    "    card.classList.add('hidden');\n"
    "    toggle.innerHTML='&#9654; Show broker log';\n"
    "    if(brokerLogInterval){clearInterval(brokerLogInterval);brokerLogInterval=null;}\n"
    "  }\n"
    "}\n"
    "\n"
    "async function refreshBrokerLog(){\n"
    "  try{\n"
    "    const entries=await api('/api/broker/log');\n"
    "    const el=$('broker-log');\n"
    "    if(!entries||entries.length===0){\n"
    "      el.textContent='No MQTT traffic yet.';\n"
    "      return;\n"
    "    }\n"
    "    const lines=entries.map(e=>{\n"
    "      const ts = e.time_str ? e.time_str : e.time.toFixed(1)+'s';\n"
    "      return ts+' ['+e.client+'] '+e.topic+' | '+e.payload;\n"
    "    });\n"
    "    el.textContent=lines.join('\\n');\n"
    "    el.scrollTop = el.scrollHeight;\n"
    "  }catch(e){}\n"
    "}\n"
    "\n"
    "function copyBrokerLog(){\n"
    "  const el = $('broker-log');\n"
    "  const text = el.textContent;\n"
    "  if (!text || text === 'No MQTT traffic yet.' || text === 'Waiting for data...') {\n"
    "    toast('Nothing to copy', 'error');\n"
    "    return;\n"
    "  }\n"
    "  const range = document.createRange();\n"
    "  range.selectNode(el);\n"
    "  window.getSelection().removeAllRanges();\n"
    "  window.getSelection().addRange(range);\n"
    "  if (document.execCommand('copy')) {\n"
    "    toast('Copied to clipboard', 'success');\n"
    "  } else {\n"
    "    toast('Copy failed', 'error');\n"
    "  }\n"
    "  window.getSelection().removeAllRanges();\n"
    "}\n"
    "\n"
    "async function parseScript(){\n"
    "  const script=$('script-input').value.trim();\n"
    "  if(!script) return toast('Please paste a script','error');\n"
    "\n"
    "  $('mapping-card').classList.add('hidden');\n"
    "  $('send-card').classList.add('hidden');\n"
    "  const r=await api('/api/script/parse',{\n"
    "    method:'POST',\n"
    "    headers:{'Content-Type':'application/json'},\n"
    "    body:JSON.stringify({script})\n"
    "  });\n"
    "\n"
    "  currentMappings=r.mappings||[];\n"
    "  renderMappings();\n"
    "  $('mapping-card').classList.remove('hidden');\n"
    "\n"
    "  scriptGpioRx=r.gpio_rx;\n"
    "  scriptGpioTx=r.gpio_tx;\n"
    "  updateGpioCard();\n"
    "  updateSendSummary();\n"
    "  toast(r.mappings.length+' variables found, GPIO checked','success');\n"
    "}\n"
    "\n"
    "function updateGpioCard(){\n"
    "  const rx=$('gpio-rx').value;\n"
    "  const tx=$('gpio-tx').value;\n"
    "  const warn=$('gpio-warning');\n"
    "  const msg=$('gpio-warning-msg');\n"
    "  const confirm=$('gpio-confirm');\n"
    "  let hasWarning=false;\n"
    "\n"
    "  if(scriptGpioRx>0||scriptGpioTx>0){\n"
    "    const parts=[];\n"
    "    if(scriptGpioRx>0) parts.push('RX=GPIO'+scriptGpioRx);\n"
    "    if(scriptGpioTx>0) parts.push('TX=GPIO'+scriptGpioTx);\n"
    "    if(rx!=scriptGpioRx||tx!=scriptGpioTx){\n"
    "      msg.innerHTML='&#9888;&#65039; Found in script: '+parts.join(', ')+'<br>Defaults differ. Please check GPIO pins.';\n"
    "      warn.classList.remove('hidden');\n"
    "      hasWarning=true;\n"
    "    }else{\n"
    "      msg.innerHTML='&#9989; Found in script: '+parts.join(', ')+' &mdash; matches';\n"
    "      warn.classList.remove('hidden');\n"
    "    }\n"
    "  }else{\n"
    "    msg.innerHTML='&#8505;&#65039; No GPIO info in script. Defaults will be used.';\n"
    "    warn.classList.remove('hidden');\n"
    "  }\n"
    "\n"
    "  confirm.checked=false;\n"
    "  $('gpio-card').classList.remove('hidden');\n"
    "  updateApplyButton();\n"
    "  $('gpio-rx').oninput=function(){updateApplyButton();updateSendSummary();};\n"
    "  $('gpio-tx').oninput=function(){updateApplyButton();updateSendSummary();};\n"
    "  confirm.onchange=updateApplyButton;\n"
    "}\n"
    "\n"
    "function updateSendSummary(){\n"
    "  const ip=$('tasmota-ip').value||'(not set)';\n"
    "  const scriptLen=$('script-input').value.length;\n"
    "  const rx=$('gpio-rx').value;\n"
    "  const tx=$('gpio-tx').value;\n"
    "  const el=$('send-summary');\n"
    "  el.innerHTML='<b>Will send to Tasmota at '+escHtml(ip)+':</b><br>'+\n"
    "    'Script: '+scriptLen+' chars &middot; GPIO: RX='+rx+', TX='+tx+' &middot; Reset Template+Module &middot; Configure MQTT &middot; Reboot';\n"
    "}\n"
    "\n"
    "function updateApplyButton(){\n"
    "  const btn=$('apply-btn');\n"
    "  if(!btn) return;\n"
    "  const confirm=$('gpio-confirm');\n"
    "  const rx=$('gpio-rx').value;\n"
    "  const tx=$('gpio-tx').value;\n"
    "  const needConfirm=(scriptGpioRx>0||scriptGpioTx>0)&&(rx!=scriptGpioRx||tx!=scriptGpioTx);\n"
    "  btn.disabled=needConfirm&&!confirm.checked;\n"
    "  const gc=$('gpio-card');\n"
    "  if(gc&&!gc.classList.contains('hidden')){\n"
    "    if(!needConfirm||confirm.checked){\n"
    "      $('send-card').classList.remove('hidden');\n"
    "    }else{\n"
    "      $('send-card').classList.add('hidden');\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "function renderMappings(){\n"
    "  const tbody=$('mapping-table');\n"
    "  tbody.innerHTML='';\n"
    "  currentMappings.forEach((m,i)=>{\n"
    "    const tr=document.createElement('tr');\n"
    "    tr.innerHTML=`\n"
    "      <td>${m.var||m.var_name}</td>\n"
    "      <td>${m.label||''}</td>\n"
    "      <td>${m.unit||''}</td>\n"
    "      <td>\n"
    "        <select data-idx=\"${i}\">\n"
    "          <option value=\"\">&mdash; don't send &mdash;</option>\n"
    "          ${LOTSE_KEYS.map(k=>`<option value=\"${k}\"${(m.lotse_key===k)?' selected':''}>${k}</option>`).join('')}\n"
    "        </select>\n"
    "      </td>`;\n"
    "    tbody.appendChild(tr);\n"
    "  });\n"
    "  tbody.querySelectorAll('select').forEach(sel=>{\n"
    "    sel.addEventListener('change',()=>{\n"
    "      const idx=parseInt(sel.dataset.idx);\n"
    "      currentMappings[idx].lotse_key=sel.value;\n"
    "    });\n"
    "  });\n"
    "}\n"
    "\n"
    "async function applyConfig(){\n"
    "  const tasmotaIp=$('tasmota-ip').value.trim();\n"
    "  if(!tasmotaIp) return toast('Please enter Tasmota IP','error');\n"
    "\n"
    "  $('apply-msg').innerHTML='<span id=\"spinner\"></span>Checking Tasmota...';\n"
    "  $('apply-msg').style.color='#666';\n"
    "\n"
    "  try{\n"
    "    const diff=await api('/api/tasmota/diff');\n"
    "    if(!diff.reachable){\n"
    "      // Tasmota unreachable — let user choose what to send\n"
    "      diffData = {\n"
    "        reachable: false,\n"
    "        differences: [\n"
    "          {item:'script', label:'Push SMI script', current:'(Tasmota unreachable)', expected:'ready to push ('+$('script-input').value.length+' chars)', needs_update:true},\n"
    "          {item:'mqtt', label:'Configure MQTT', current:'(Tasmota unreachable)', expected:'MQTT host, port, SetOption19', needs_update:true}\n"
    "        ]\n"
    "      };\n"
    "      renderDiffModal();\n"
    "      $('diff-modal').classList.remove('hidden');\n"
    "      $('apply-msg').textContent='';\n"
    "      return;\n"
    "    }\n"
    "    const needsUpdate=diff.differences.filter(d=>d.needs_update);\n"
    "    if(needsUpdate.length===0){\n"
    "      $('apply-msg').innerHTML='&#9989; Tasmota already up to date';\n"
    "      $('apply-msg').style.color='#2e7d32';\n"
    "      toast('No differences — Tasmota up to date','success');\n"
    "      return;\n"
    "    }\n"
    "    // Show modal with differences\n"
    "    diffData=diff;\n"
    "    renderDiffModal();\n"
    "    $('diff-modal').classList.remove('hidden');\n"
    "    $('apply-msg').textContent='';\n"
    "  }catch(e){\n"
    "    // Fallback — let user choose what to send\n"
    "    diffData = {\n"
    "      reachable: false,\n"
    "      differences: [\n"
    "        {item:'script', label:'Push SMI script', current:'(error checking Tasmota)', expected:'ready to push ('+$('script-input').value.length+' chars)', needs_update:true},\n"
    "        {item:'mqtt', label:'Configure MQTT', current:'(error checking Tasmota)', expected:'MQTT host, port, SetOption19', needs_update:true}\n"
    "      ]\n"
    "    };\n"
    "    renderDiffModal();\n"
    "    $('diff-modal').classList.remove('hidden');\n"
    "    $('apply-msg').textContent='';\n"
    "  }\n"
    "}\n"
    "\n"
    "function renderDiffModal(){\n"
    "  const container=$('diff-items');\n"
    "  container.innerHTML='';\n"
    "  diffData.differences.forEach(d=>{\n"
    "    const checked=d.needs_update?'checked':'';\n"
    "    const row=document.createElement('div');\n"
    "    row.style.cssText='padding:8px 0;border-bottom:1px solid #eee;font-size:13px';\n"
    "    row.innerHTML=\n"
    "      '<label style=\"display:flex;align-items:flex-start;gap:8px;cursor:pointer;font-weight:400\">'+\n"
    "        '<input type=\"checkbox\" class=\"diff-cb\" data-item=\"'+escHtml(d.item)+'\" '+checked+\n"
    "          (d.needs_update?'':' disabled')+'>'+\n"
    "        '<div>'+\n"
    "          '<b>'+escHtml(d.label)+'</b><br>'+\n"
    "          '<span style=\"color:#c62828\">&#10060; '+escHtml(d.current)+'</span> &rarr; '+\n"
    "          '<span style=\"color:#2e7d32\">'+escHtml(d.expected)+'</span>'+\n"
    "        '</div>'+\n"
    "      '</label>';\n"
    "    container.appendChild(row);\n"
    "  });\n"
    "}\n"
    "\n"
    "function closeDiffModal(){\n"
    "  $('diff-modal').classList.add('hidden');\n"
    "}\n"
    "\n"
    "function sendSelectedActions(){\n"
    "  const cbs=document.querySelectorAll('#diff-items .diff-cb:checked');\n"
    "  const actions=Array.from(cbs).map(cb=>cb.dataset.item);\n"
    "  closeDiffModal();\n"
    "  reallySend(actions);\n"
    "}\n"
    "\n"
    "async function reallySend(actions){\n"
    "  const tasmotaIp=$('tasmota-ip').value.trim();\n"
    "  $('apply-msg').innerHTML='<span id=\"spinner\"></span>Sending...';\n"
    "  $('apply-msg').style.color='#666';\n"
    "  try{\n"
    "    const r=await api('/api/tasmota/configure',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({\n"
    "        tasmota_ip:tasmotaIp,\n"
    "        script:$('script-input').value,\n"
    "        mappings:currentMappings,\n"
    "        region:$('region').value,\n"
    "        node_decimal:parseInt($('node-decimal').value)||0,\n"
    "        gpio_rx:parseInt($('gpio-rx').value)||3,\n"
    "        gpio_tx:parseInt($('gpio-tx').value)||1,\n"
    "        actions:actions\n"
    "      })\n"
    "    });\n"
    "    let statusColor='#2e7d32';\n"
    "    let toastType='success';\n"
    "    if(r.verified&&r.match){\n"
    "      $('apply-msg').innerHTML='&#9989; '+r.message;\n"
    "    }else if(r.verified&&!r.match){\n"
    "      $('apply-msg').innerHTML='&#9888;&#65039; '+r.message;\n"
    "      statusColor='#e65100';\n"
    "      toastType='error';\n"
    "    }else{\n"
    "      $('apply-msg').innerHTML='&#9888;&#65039; '+r.message;\n"
    "      statusColor='#c62828';\n"
    "      toastType='error';\n"
    "    }\n"
    "    $('apply-msg').style.color=statusColor;\n"
    "    toast(r.message, toastType);\n"
    "    refreshStatus();\n"
    "  }catch(e){\n"
    "    $('apply-msg').textContent='Failed';\n"
    "    $('apply-msg').style.color='#c62828';\n"
    "  }\n"
    "}\n"
    "\n"
    "async function discoverTasmota(){\n"
    "  $('discover-msg').textContent='Searching...';\n"
    "  try{\n"
    "    const r=await api('/api/tasmota/discover',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({ip:$('tasmota-ip').value.trim()})\n"
    "    });\n"
    "    if(r.success){\n"
    "      $('discover-msg').textContent='&#9989; Tasmota found';\n"
    "      toast('Tasmota reachable','success');\n"
    "    }else{\n"
    "      $('discover-msg').textContent='&#10060; No Tasmota at this IP';\n"
    "      toast('Tasmota not reachable','error');\n"
    "    }\n"
    "  }catch(e){\n"
    "    $('discover-msg').textContent='&#10060; Error';\n"
    "  }\n"
    "}\n"
    "\n"
    "async function verifyTasmota(){\n"
    "  const msg=$('verify-msg');\n"
    "  msg.innerHTML='<span id=\"spinner\"></span> Reading...';\n"
    "  try{\n"
    "    const r=await api('/api/tasmota/verify');\n"
    "    if(!r.reachable){\n"
    "      msg.innerHTML='&#10060; Tasmota unreachable';\n"
    "      return;\n"
    "    }\n"
    "    if(r.match){\n"
    "      msg.innerHTML='&#9989; Script is loaded and running';\n"
    "    }else if(r.script_running === false){\n"
    "      msg.innerHTML='&#9888;&#65039; No script loaded on Tasmota';\n"
    "    }else{\n"
    "      msg.innerHTML='&#9888;&#65039; Script differs from stored config';\n"
    "    }\n"
    "    toast('Tasmota '+(r.reachable?'reachable':'unreachable'), r.reachable?'info':'error');\n"
    "  }catch(e){\n"
    "    msg.textContent='&#10060; Error';\n"
    "  }\n"
    "}\n"
    "\n"
    "async function detectNodeHash(){\n"
    "  const btn=$('node-hash').parentNode.querySelector('button');\n"
    "  const orig=btn.innerHTML;\n"
    "  btn.innerHTML='Detecting...';\n"
    "  btn.disabled=true;\n"
    "  try{\n"
    "    const r=await api('/api/mesh/discover');\n"
    "    if(r.nodes&&r.nodes.length>0){\n"
    "      $('node-hash').value=r.nodes[0].hash;\n"
    "      toast('Detected hash: '+r.nodes[0].hash,'success');\n"
    "    }else{\n"
    "      toast('No Meshtastic nodes found in MQTT traffic','error');\n"
    "    }\n"
    "  }catch(e){\n"
    "    toast('Detection failed','error');\n"
    "  }\n"
    "  btn.innerHTML=orig;\n"
    "  btn.disabled=false;\n"
    "}\n"
    "\n"
    "async function saveConfig(){\n"
    "  await api('/api/config',{\n"
    "    method:'POST',\n"
    "    headers:{'Content-Type':'application/json'},\n"
    "    body:JSON.stringify({\n"
    "      tasmota_ip:$('tasmota-ip').value,\n"
    "      region:$('region').value,\n"
    "      node_decimal:parseInt($('node-decimal').value)||0,\n"
    "      node_hash:$('node-hash').value,\n"
    "      send_interval:parseInt($('send-interval').value)||300,\n"
    "      gpio_rx:parseInt($('gpio-rx').value)||3,\n"
    "      gpio_tx:parseInt($('gpio-tx').value)||1,\n"
    "      script:$('script-input').value,\n"
    "      mappings:currentMappings\n"
    "    })\n"
    "  });\n"
    "  toast('Saved','success');\n"
    "}\n"
    "\n"
    "async function factoryReset(){\n"
    "  if(!confirm('Really reset to factory defaults? The device will reboot into AP mode.')) return;\n"
    "  const msg=$('reset-msg');\n"
    "  msg.textContent='Resetting...';\n"
    "  try{\n"
    "    await api('/api/config',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({configured:false,wifi_ssid:'',wifi_pass:'',tasmota_ip:'',region:'',node_decimal:0,send_interval:300,script:'',mappings:[]})\n"
    "    });\n"
    "    toast('Reset! Please restart the device.','success');\n"
    "    msg.textContent='OK &mdash; power cycle the device (or press RST)';\n"
    "  }catch(e){\n"
    "    msg.textContent='Failed';\n"
    "  }\n"
    "}\n"
    "\n"
    "init();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n";
static const size_t HTML_INDEX_HTML_LEN = sizeof(HTML_INDEX_HTML) - 1;
static const char *HTML_INDEX_HTML_TYPE = "text/html";
static const char *HTML_INDEX_HTML_PATH = "/index.html";
